### ISSUE TITLE
See issue raised on teams

### ISSUE THREAD

**Issue by mattloose** [Adoni5/cnv_from_bam#21]
See teams.

**Comment by Adoni5** [comment]
Double check how the binning for the final Copy Number works based on the mapping counts in 1000 base bins.

We are getting more bins than we should do, the amount being `total contig length / bin width = number of extra bins`
Potential solution is to round bin width down to nearest 1000

**Comment by Adoni5** [comment]
Add the Equation for calculation of Bins to the README
Will let people (including me) how we calculate CNV

**Comment by Adoni5** [comment]
Closed in #20
